### PR TITLE
update HGDP pops

### PR DESCRIPTION
**Pull request by KoalaQin**
As we are going to use update pop labels for HGDP samples in v4, aligning with the labels used by [this publication](https://www.science.org/doi/10.1126/science.aay5012?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub++0pubmed&) and Alicia Martin's group's [preprint](https://www.biorxiv.org/content/10.1101/2023.01.23.525248v1).

### CODE REVIEW

**Review by jkgoodrich — APPROVED** [review]

**Review by jkgoodrich — CHANGES_REQUESTED** [review]
Actually, can you update `TGP_POP_NAMES` too?

**Comment by KoalaQin** [comment]
I thought there's no change in TGP pops?

**Comment by KoalaQin** [comment]
> HGDP_POP_NAMES



> Actually, can you update `HGDP_POP_NAMES` too?

I can'f find `HGDP_POP_NAMES`in gnomad_methods, where is it?

**Comment by jkgoodrich** [comment]
oh, maybe we don't have any, I just assumed since we have one for TGP

**Review by jkgoodrich — APPROVED** [review]

**Comment by KoalaQin** [comment]
Maybe we can copy what we will settle for gnomAD browser to store them as `HGDP_POP_names`.

**Pull request merged**
