### PR TITLE
Update csq impact lists with v105 splice terms

### PR DESCRIPTION
**Pull request by mike-w-wilson**
Adds: splice_donor_5th_base_variant, splice_donor_region_variant , and splice_polypyrimidine_tract_variant

### CODE REVIEW

**Review by ch-kr — APPROVED** [review]
these changes LGTM. I have a few notes below of edits if we want to be fully consistent with https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html?redirect=no:

HIGH:
- transcript_amplification (previously MEDIUM)

These are also now HIGH but I don't love moving these into high impact:
- feature_elongation
- feature_truncation

MODIFIER:
- coding_sequence_variant (previously LOW impact)
- coding_transcript_variant (looks new)
- sequence_variant (looks new)

**Comment by ch-kr** [comment]
yeah, I agree we need to decide whether to imitate VEP or just loosely follow their mapping with some adjustments. I was initially thinking we'd stay consistent with VEP, but I don't think that actually serves us in our potential downstream applications using these groups, so I vote we do the latter (use all of VEP's listed consequence terms and adjust the associated impacts where needed).

maybe we should move `start_lost` and `transcript_amplification` back to medium, keep `feature_elongation`/`feature_truncation`/`coding_sequence_variant` where they are currently (non-coding for the first two and low for the last one), add `coding_transcript_variant` to `CSQ_CODING_LOW_IMPACT` , and add `sequence_variant` to `CSQ_NON_CODING`?

^I know this is more complex than the initial PR, so I'd be happy to merge this PR and start the discussion via slack to finalize which terms should go where

**Comment by mike-w-wilson** [comment]
@ch-kr  That sounds good to me. I've made updates to the PR. Would you still like to start the slack discussion?

**Review by ch-kr — APPROVED** [review]

**Comment by ch-kr** [comment]
let's merge -- I have a meeting with Kaitlin next week and will plan to ask her about these then (and move into a larger public channel if needed)

**Pull request merged**
